# Generated by Django 5.1 on 2024-08-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Book_title',
            new_name='title',
        ),
    ]
